### ISSUE TITLE
Assign Default Branch: Initial_Contrib -> master

### ISSUE THREAD

**Issue by tobiasmo1** [edgexfoundry-holding/device-camera-go#4]
Since the initial commit to this repository was made to Initial_Contrib, it caused GitHub to automatically assign this as the default branch. This is not intended.

Need to update Repository / Settings / Branch to indicate 'master' is the default branch.

The "Initial_Contrib" branch can also then be deleted.

**Comment by jamesrgregg** [comment]
Submitted request to the helpdesk.  The release engineer can make the changes to set master as Default.  I don't have the permissions.
[l#68138]

**Comment by MightyNerdEric** [comment]
Done. "master" is now the default branch.
